# Generated by Django 4.0.6 on 2022-09-21 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='shop.productcategory')),
            ],
            options={
                'verbose_name_plural': 'categories',
                'unique_together': {('name', 'parent')},
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('stock', models.CharField(choices=[('Yes', 'In Stock'), ('No', 'Out of Stock')], max_length=10)),
                ('model_number', models.CharField(blank=True, max_length=20, null=True)),
                ('rating', models.IntegerField(default=0)),
                ('price', models.FloatField()),
                ('discount_price', models.FloatField(blank=True, null=True)),
                ('save', models.FloatField(blank=True, null=True)),
                ('percent_save', models.FloatField(blank=True, null=True)),
                ('description', models.TextField()),
                ('last_sold', models.IntegerField(default=0)),
                ('last_sold_time', models.DateTimeField()),
                ('color', models.CharField(choices=[('RED', 'RED'), ('BLUE', 'BLUE'), ('GREEN', 'GREEN'), ('GREY', 'GREY'), ('ORANGE', 'ORANGE'), ('BROWN', 'BROWN')], max_length=10)),
                ('total_quantity', models.IntegerField()),
                ('slug', models.SlugField()),
                ('wishlist', models.BooleanField(default=False)),
                ('image', models.ImageField(upload_to='')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.productcategory')),
            ],
        ),
    ]
