# Generated by Django 4.0.6 on 2022-10-04 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_item_date_posted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='discount_price',
        ),
        migrations.RemoveField(
            model_name='item',
            name='price',
        ),
        migrations.RemoveField(
            model_name='item',
            name='save',
        ),
        migrations.RemoveField(
            model_name='item',
            name='total_quantity',
        ),
        migrations.AddField(
            model_name='productcategory',
            name='image',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='percent_save',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
