# Generated by Django 4.0.6 on 2022-10-04 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_item_discount_price_remove_item_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='image',
        ),
        migrations.AddField(
            model_name='productcategory',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='blog_images'),
        ),
    ]
