# Generated by Django 4.0.6 on 2022-10-06 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_remove_productcategory_image_productcategory_images'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productcategory',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='item',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='collection'),
        ),
        migrations.AlterUniqueTogether(
            name='productcategory',
            unique_together={('name', 'images', 'parent')},
        ),
    ]
