# Generated by Django 4.0.6 on 2022-10-06 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_productcategory_unique_together_item_quantity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='image',
            new_name='images',
        ),
        migrations.AddField(
            model_name='item',
            name='images1',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
